/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopappgui.Frames;

import adminDataModel.DataContainer;
import adminDataModel.Event;
import adminDataModel.Show;
import adminDataModel.Venue;
import java.awt.Color;
import validation.*;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.temporal.Temporal;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import validation.CustomValidator;

public class FormAddShow extends javax.swing.JFrame {

    DataContainer admin = DataContainer.getInstance();
    DefaultComboBoxModel<Event> eventModel = new DefaultComboBoxModel();
    DefaultComboBoxModel<Venue> venueModel = new DefaultComboBoxModel();

    public FormAddShow() {
        initComponents();

        // Set custom visuals
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/addForm.png")));
        this.setLocationRelativeTo(null); // Centre window
        initComboBoxes();
    }

    private void initComboBoxes() {
        for (Event curr : admin.getEventList()) {
            eventModel.addElement(curr);
        }
        for (Venue curr : admin.getVenueList()) {
            venueModel.addElement(curr);
        }
    }

    public void setSelectedEvent(Event e) {
        cmbEvent.setSelectedItem(e);
    }

    public void setSelectedVenue(Venue v) {
        cmbVenue.setSelectedItem(v);
    }

    private void createShow() {
        Event e = (Event) cmbEvent.getSelectedItem();
        Venue v = (Venue) cmbVenue.getSelectedItem();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = dateFormat.format(jdcStartDate.getDate());
        LocalDate ld = LocalDate.parse(dateString);
        dateFormat = new SimpleDateFormat("HH:mm:ss");
        dateString = dateFormat.format(spnTime.getValue());
        LocalTime lt = LocalTime.parse(dateString);
        LocalDateTime st = LocalDateTime.of(ld, lt);
        admin.addNewShow(new Show(e, v, st));
    }

    private void validateForm() {
        createShow();
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pForm = new javax.swing.JPanel();
        pShowDetails = new javax.swing.JPanel();
        pHeader2 = new javax.swing.JPanel();
        lbShowDetails = new javax.swing.JLabel();
        pContent2 = new javax.swing.JPanel();
        pLabels1 = new javax.swing.JPanel();
        lbEvent = new javax.swing.JLabel();
        lbVenue = new javax.swing.JLabel();
        pInputs1 = new javax.swing.JPanel();
        pEventPicker = new javax.swing.JPanel();
        cmbEvent = new javax.swing.JComboBox<Event>();
        btnAddEvent = new javax.swing.JButton();
        pVenuePicker = new javax.swing.JPanel();
        cmbVenue = new javax.swing.JComboBox<>();
        btnAddVenue = new javax.swing.JButton();
        pLabels2 = new javax.swing.JPanel();
        lbStartDate = new javax.swing.JLabel();
        lbStartTime = new javax.swing.JLabel();
        pInputs2 = new javax.swing.JPanel();
        jdcStartDate = new com.toedter.calendar.JDateChooser();
        spnTime = new javax.swing.JSpinner(new SpinnerDateModel());
        pConcessions = new javax.swing.JPanel();
        pHeader3 = new javax.swing.JPanel();
        lbConcessions = new javax.swing.JLabel();
        pContent3 = new javax.swing.JPanel();
        pLabels4 = new javax.swing.JPanel();
        lbStudentDiscount = new javax.swing.JLabel();
        lbChildDiscount = new javax.swing.JLabel();
        pInputs4 = new javax.swing.JPanel();
        spnStudentDiscount = new javax.swing.JSpinner(new SpinnerDateModel());
        spnChildDiscount = new javax.swing.JSpinner(new SpinnerDateModel());
        pPriceBands = new javax.swing.JPanel();
        pHeader4 = new javax.swing.JPanel();
        lbPriceBands = new javax.swing.JLabel();
        pContent4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePriceBands = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtPriceBand = new javax.swing.JTextField();
        btnAddPriceBand = new javax.swing.JButton();
        spnSeats = new javax.swing.JSpinner(new SpinnerDateModel());
        txtCost = new javax.swing.JFormattedTextField();
        pConfirmArea = new javax.swing.JPanel();
        pInputs = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Show");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pForm.setBackground(new java.awt.Color(255, 255, 255));
        pForm.setForeground(new java.awt.Color(204, 204, 204));

        pShowDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader2.setBackground(new java.awt.Color(255, 255, 255));

        lbShowDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbShowDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/show.png"))); // NOI18N
        lbShowDetails.setText("Show Details");
        lbShowDetails.setToolTipText("");

        javax.swing.GroupLayout pHeader2Layout = new javax.swing.GroupLayout(pHeader2);
        pHeader2.setLayout(pHeader2Layout);
        pHeader2Layout.setHorizontalGroup(
            pHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbShowDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pHeader2Layout.setVerticalGroup(
            pHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbShowDetails)
        );

        pContent2.setBackground(new java.awt.Color(255, 255, 255));
        pContent2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels1.setBackground(new java.awt.Color(255, 255, 255));
        pLabels1.setLayout(new java.awt.GridLayout(2, 1, 11, 11));

        lbEvent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEvent.setForeground(new java.awt.Color(42, 42, 42));
        lbEvent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEvent.setText("Event*");
        pLabels1.add(lbEvent);

        lbVenue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVenue.setForeground(new java.awt.Color(42, 42, 42));
        lbVenue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbVenue.setText("Venue*");
        pLabels1.add(lbVenue);

        pInputs1.setBackground(new java.awt.Color(255, 255, 255));
        pInputs1.setLayout(new java.awt.GridLayout(2, 2, 5, 11));

        pEventPicker.setLayout(new javax.swing.BoxLayout(pEventPicker, javax.swing.BoxLayout.LINE_AXIS));

        cmbEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbEvent.setModel(eventModel);
        pEventPicker.add(cmbEvent);

        btnAddEvent.setBackground(new java.awt.Color(255, 255, 255));
        btnAddEvent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddEvent.setText("+");
        btnAddEvent.setIconTextGap(1);
        btnAddEvent.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnAddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventActionPerformed(evt);
            }
        });
        pEventPicker.add(btnAddEvent);

        pInputs1.add(pEventPicker);

        pVenuePicker.setLayout(new javax.swing.BoxLayout(pVenuePicker, javax.swing.BoxLayout.LINE_AXIS));

        cmbVenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbVenue.setModel(venueModel);
        pVenuePicker.add(cmbVenue);

        btnAddVenue.setBackground(new java.awt.Color(255, 255, 255));
        btnAddVenue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddVenue.setText("+");
        btnAddVenue.setIconTextGap(1);
        btnAddVenue.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnAddVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVenueActionPerformed(evt);
            }
        });
        pVenuePicker.add(btnAddVenue);

        pInputs1.add(pVenuePicker);

        pLabels2.setBackground(new java.awt.Color(255, 255, 255));
        pLabels2.setLayout(new java.awt.GridLayout(2, 1, 11, 11));

        lbStartDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbStartDate.setForeground(new java.awt.Color(42, 42, 42));
        lbStartDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStartDate.setText("Start Date*");
        pLabels2.add(lbStartDate);

        lbStartTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbStartTime.setForeground(new java.awt.Color(42, 42, 42));
        lbStartTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStartTime.setText("Start Time*");
        pLabels2.add(lbStartTime);

        pInputs2.setBackground(new java.awt.Color(255, 255, 255));
        pInputs2.setLayout(new java.awt.GridLayout(2, 1, 2, 11));

        jdcStartDate.setToolTipText("");
        jdcStartDate.setDate(new Date());
        jdcStartDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdcStartDate.setMinSelectableDate(new java.util.Date(-2208985112000L));
        pInputs2.add(jdcStartDate);

        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(spnTime,"HH:mm");
        spnTime.setEditor(timeEditor);
        spnTime.setValue(new Date());
        spnTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pInputs2.add(spnTime);

        javax.swing.GroupLayout pContent2Layout = new javax.swing.GroupLayout(pContent2);
        pContent2.setLayout(pContent2Layout);
        pContent2Layout.setHorizontalGroup(
            pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLabels1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(pLabels2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pInputs1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pInputs2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pContent2Layout.setVerticalGroup(
            pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLabels1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pInputs2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pLabels2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pShowDetailsLayout = new javax.swing.GroupLayout(pShowDetails);
        pShowDetails.setLayout(pShowDetailsLayout);
        pShowDetailsLayout.setHorizontalGroup(
            pShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pShowDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pShowDetailsLayout.setVerticalGroup(
            pShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pShowDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pConcessions.setBackground(new java.awt.Color(255, 255, 255));

        pHeader3.setBackground(new java.awt.Color(255, 255, 255));

        lbConcessions.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbConcessions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/concessions.png"))); // NOI18N
        lbConcessions.setText("Concessions");
        lbConcessions.setToolTipText("");

        javax.swing.GroupLayout pHeader3Layout = new javax.swing.GroupLayout(pHeader3);
        pHeader3.setLayout(pHeader3Layout);
        pHeader3Layout.setHorizontalGroup(
            pHeader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbConcessions, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pHeader3Layout.setVerticalGroup(
            pHeader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbConcessions)
        );

        pContent3.setBackground(new java.awt.Color(255, 255, 255));
        pContent3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels4.setBackground(new java.awt.Color(255, 255, 255));
        pLabels4.setLayout(new java.awt.GridLayout(2, 1, 11, 11));

        lbStudentDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbStudentDiscount.setForeground(new java.awt.Color(42, 42, 42));
        lbStudentDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStudentDiscount.setText("Student %");
        pLabels4.add(lbStudentDiscount);

        lbChildDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbChildDiscount.setForeground(new java.awt.Color(42, 42, 42));
        lbChildDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbChildDiscount.setText("Child %");
        pLabels4.add(lbChildDiscount);

        pInputs4.setBackground(new java.awt.Color(255, 255, 255));
        pInputs4.setLayout(new java.awt.GridLayout(2, 1, 2, 11));

        spnStudentDiscount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnStudentDiscount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        pInputs4.add(spnStudentDiscount);

        spnChildDiscount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnChildDiscount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        pInputs4.add(spnChildDiscount);

        javax.swing.GroupLayout pContent3Layout = new javax.swing.GroupLayout(pContent3);
        pContent3.setLayout(pContent3Layout);
        pContent3Layout.setHorizontalGroup(
            pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pLabels4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInputs4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pContent3Layout.setVerticalGroup(
            pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pInputs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLabels4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pConcessionsLayout = new javax.swing.GroupLayout(pConcessions);
        pConcessions.setLayout(pConcessionsLayout);
        pConcessionsLayout.setHorizontalGroup(
            pConcessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConcessionsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pConcessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pConcessionsLayout.setVerticalGroup(
            pConcessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConcessionsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pPriceBands.setBackground(new java.awt.Color(255, 255, 255));

        pHeader4.setBackground(new java.awt.Color(255, 255, 255));

        lbPriceBands.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbPriceBands.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/priceBands.png"))); // NOI18N
        lbPriceBands.setText("Price Bands");
        lbPriceBands.setToolTipText("");

        javax.swing.GroupLayout pHeader4Layout = new javax.swing.GroupLayout(pHeader4);
        pHeader4.setLayout(pHeader4Layout);
        pHeader4Layout.setHorizontalGroup(
            pHeader4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPriceBands, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pHeader4Layout.setVerticalGroup(
            pHeader4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPriceBands)
        );

        pContent4.setBackground(new java.awt.Color(255, 255, 255));
        pContent4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jScrollPane1.setBackground(new java.awt.Color(178, 178, 178));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jTablePriceBands.setAutoCreateRowSorter(true);
        jTablePriceBands.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablePriceBands.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Standard",  new Integer(1),  new Double(0.0)}
            },
            new String [] {
                "Price Band Name", "Seats", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePriceBands.setColumnSelectionAllowed(true);
        jTablePriceBands.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTablePriceBands);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtPriceBand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPriceBand.setText("Price Band");
        txtPriceBand.setToolTipText("");
        txtPriceBand.setName("Event Name"); // NOI18N

        btnAddPriceBand.setBackground(new java.awt.Color(255, 255, 255));
        btnAddPriceBand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddPriceBand.setText("+");
        btnAddPriceBand.setIconTextGap(1);
        btnAddPriceBand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPriceBandActionPerformed(evt);
            }
        });

        spnSeats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnSeats.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));

        txtCost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0.00"))));
        txtCost.setText("0.00");
        txtCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtPriceBand, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPriceBand)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPriceBand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPriceBand)
                    .addComponent(spnSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pContent4Layout = new javax.swing.GroupLayout(pContent4);
        pContent4.setLayout(pContent4Layout);
        pContent4Layout.setHorizontalGroup(
            pContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pContent4Layout.setVerticalGroup(
            pContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pPriceBandsLayout = new javax.swing.GroupLayout(pPriceBands);
        pPriceBands.setLayout(pPriceBandsLayout);
        pPriceBandsLayout.setHorizontalGroup(
            pPriceBandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPriceBandsLayout.createSequentialGroup()
                .addComponent(pHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pContent4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pPriceBandsLayout.setVerticalGroup(
            pPriceBandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPriceBandsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pFormLayout = new javax.swing.GroupLayout(pForm);
        pForm.setLayout(pFormLayout);
        pFormLayout.setHorizontalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pShowDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pConcessions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pPriceBands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        pFormLayout.setVerticalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pShowDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pConcessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pPriceBands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pConfirmArea.setBackground(new java.awt.Color(242, 242, 242));
        pConfirmArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pInputs.setBackground(new java.awt.Color(242, 242, 242));
        pInputs.setLayout(new java.awt.GridLayout(1, 1, 6, 4));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/tick.png"))); // NOI18N
        btnSave.setText("Create");
        btnSave.setIconTextGap(1);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pInputs.add(btnSave);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setIconTextGap(1);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pInputs.add(btnCancel);

        javax.swing.GroupLayout pConfirmAreaLayout = new javax.swing.GroupLayout(pConfirmArea);
        pConfirmArea.setLayout(pConfirmAreaLayout);
        pConfirmAreaLayout.setHorizontalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pConfirmAreaLayout.setVerticalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pConfirmArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pConfirmArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        validateForm();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventActionPerformed
        FormAddEvent objWindow = new FormAddEvent();
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnAddEventActionPerformed

    private void btnAddVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVenueActionPerformed
        FormAddVenue objWindow = new FormAddVenue();
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnAddVenueActionPerformed

    private void btnAddPriceBandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPriceBandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPriceBandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddShow().setVisible(true);
            }
        });
        DataContainer.disposeInstance();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnAddPriceBand;
    private javax.swing.JButton btnAddVenue;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Event> cmbEvent;
    private javax.swing.JComboBox<Venue> cmbVenue;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePriceBands;
    private com.toedter.calendar.JDateChooser jdcStartDate;
    private javax.swing.JLabel lbChildDiscount;
    private javax.swing.JLabel lbConcessions;
    private javax.swing.JLabel lbEvent;
    private javax.swing.JLabel lbPriceBands;
    private javax.swing.JLabel lbShowDetails;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbStartTime;
    private javax.swing.JLabel lbStudentDiscount;
    private javax.swing.JLabel lbVenue;
    private javax.swing.JPanel pConcessions;
    private javax.swing.JPanel pConfirmArea;
    private javax.swing.JPanel pContent2;
    private javax.swing.JPanel pContent3;
    private javax.swing.JPanel pContent4;
    private javax.swing.JPanel pEventPicker;
    private javax.swing.JPanel pForm;
    private javax.swing.JPanel pHeader2;
    private javax.swing.JPanel pHeader3;
    private javax.swing.JPanel pHeader4;
    private javax.swing.JPanel pInputs;
    private javax.swing.JPanel pInputs1;
    private javax.swing.JPanel pInputs2;
    private javax.swing.JPanel pInputs4;
    private javax.swing.JPanel pLabels1;
    private javax.swing.JPanel pLabels2;
    private javax.swing.JPanel pLabels4;
    private javax.swing.JPanel pPriceBands;
    private javax.swing.JPanel pShowDetails;
    private javax.swing.JPanel pVenuePicker;
    private javax.swing.JSpinner spnChildDiscount;
    private javax.swing.JSpinner spnSeats;
    private javax.swing.JSpinner spnStudentDiscount;
    private javax.swing.JSpinner spnTime;
    private javax.swing.JFormattedTextField txtCost;
    private javax.swing.JTextField txtPriceBand;
    // End of variables declaration//GEN-END:variables

}
