/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopappgui.Frames;

import adminDataModel.DataContainer;
import adminDataModel.Event;
import adminDataModel.Venue;
import adminDataModel.Show;
import adminDataModel.Booking;
import adminDataModel.BookingStatus;
import adminDataModel.Customer;
import validation.*;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Month;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;

public class FormAddAdvertisement extends javax.swing.JFrame {

    DataContainer admin = DataContainer.getInstance();
    DefaultComboBoxModel<Event> eventModel = new DefaultComboBoxModel();
    DefaultComboBoxModel<Venue> venueModel = new DefaultComboBoxModel();
    DefaultComboBoxModel<LocalTime> timeModel = new DefaultComboBoxModel();
    DefaultComboBoxModel<Month> monthModel = new DefaultComboBoxModel();
    DefaultComboBoxModel<LocalDate> dateModel = new DefaultComboBoxModel();
    //DefaultComboBoxModel<LocalDateTime> priceModel = new DefaultComboBoxModel();
    private boolean isDisposing;

    /**
     * Creates new form AddUserFrame
     */
    public FormAddAdvertisement() {
        initComponents();
        admin.registerObserver(admin);
        // Set custom visuals
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/addForm.png")));
        this.setLocationRelativeTo(null); // Centre window

        addEvents(null);
//        addVenues(null);
//        addTimes();
        this.isDisposing = false;
    }

    private void addEvents(Venue v) {
        eventModel.removeAllElements();
        if (v == null) {
            for (Event curr : admin.getEventList()) {
                eventModel.addElement(curr);
            }
        } else {
            for (Show curr : admin.getShowList()) {
                if (curr.getVenue() == v) {
                    eventModel.addElement(curr.getEvent());
                }
            }
        }
    }

    public void setSelectedEvent(Event e) {
        cmbEvent.setSelectedItem(e);
    }

    //DOES OT HANDLE PRICE BANDS YET
    private void addAdvert() {
//        Customer c = new Customer(txtUserEmail.getText());
//        for (Customer curr : admin.getPeopleList()) {
//            if (cmbEvent.getItemAt(WIDTH)  txtUserEmail.getText().equals(curr.getEmail())) {
//                c = curr;
//                break;
//            }
//        }
//        Show s = new Show((Event) cmbEvent.getSelectedItem(), (Venue) cmbVenue.getSelectedItem(), (LocalDateTime) cmbTime.getSelectedItem());
//        int seats = (int) spnSeats.getValue();
//        Booking b = new Booking(c, s, BookingStatus.Upcoming, seats * 15, seats);
//        admin.addNewBooking(b);
    }

    private boolean doesUserExist(String email) {
        //Do stuff that iterates through the model to see if the user exists
        return false;
    }

    private boolean isUserGuest(String email) {
        //Check if existant user is guest or not
        return false;
    }

    private void checkUserExists(String email) {
//        if (doesUserExist(email)) {
//            if (isUserGuest(email)) {
//                if (dialog("A User does not exists with the entered email, do you want to register a "
//                        + "new user with this email (Yes) or continue as a guest booking (No)?") == YES_OPTION) {
//                    txtUserEmail.setText("OPEN NEW USER SCREEN MAKE GUEST TO USER");
//                } else {
//                    txtUserEmail.setText("CONTINUE AS GUEST");
//                }
//            } else {
//                txtUserEmail.setText("USER EXISTS");
//            }
//        } else if (dialog("A User does not exists with the entered email, do you want to register a new "
//                + "user with this email (Yes) or continue as a guest booking (No)?") == YES_OPTION) {
//            txtUserEmail.setText("OPEN NEW USER SCREEN");
//        } else {
//            txtUserEmail.setText("CONTINUE AS GUEST");
//        }
    }

    private int dialog(String msg) {
        return JOptionPane.showConfirmDialog(this, msg, "User not found?", YES_NO_OPTION, QUESTION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pForm = new javax.swing.JPanel();
        pEventDetails = new javax.swing.JPanel();
        pHeader1 = new javax.swing.JPanel();
        lbBookingDetails = new javax.swing.JLabel();
        pContent1 = new javax.swing.JPanel();
        pLabels1 = new javax.swing.JPanel();
        lbUserEmail = new javax.swing.JLabel();
        lbEvent = new javax.swing.JLabel();
        lbVenue = new javax.swing.JLabel();
        pInputs1 = new javax.swing.JPanel();
        pEventPicker = new javax.swing.JPanel();
        cmbEvent = new javax.swing.JComboBox<Event>();
        jdcScheduleDate = new com.toedter.calendar.JDateChooser();
        jdcClosingDate = new com.toedter.calendar.JDateChooser();
        pConfirmArea = new javax.swing.JPanel();
        pInputs = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Advertisement");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pForm.setBackground(new java.awt.Color(255, 255, 255));
        pForm.setForeground(new java.awt.Color(204, 204, 204));

        pEventDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader1.setBackground(new java.awt.Color(255, 255, 255));

        lbBookingDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbBookingDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/venue.png"))); // NOI18N
        lbBookingDetails.setText("Advertisement");
        lbBookingDetails.setToolTipText("");

        javax.swing.GroupLayout pHeader1Layout = new javax.swing.GroupLayout(pHeader1);
        pHeader1.setLayout(pHeader1Layout);
        pHeader1Layout.setHorizontalGroup(
            pHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBookingDetails)
        );
        pHeader1Layout.setVerticalGroup(
            pHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBookingDetails)
        );

        pContent1.setBackground(new java.awt.Color(255, 255, 255));
        pContent1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels1.setBackground(new java.awt.Color(255, 255, 255));
        pLabels1.setLayout(new java.awt.GridLayout(3, 1, 11, 11));

        lbUserEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUserEmail.setForeground(new java.awt.Color(42, 42, 42));
        lbUserEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUserEmail.setText("Event*");
        pLabels1.add(lbUserEmail);

        lbEvent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEvent.setForeground(new java.awt.Color(42, 42, 42));
        lbEvent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEvent.setText("Schedule Date*");
        pLabels1.add(lbEvent);

        lbVenue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVenue.setForeground(new java.awt.Color(42, 42, 42));
        lbVenue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbVenue.setText("Closing Date*");
        pLabels1.add(lbVenue);

        pInputs1.setBackground(new java.awt.Color(255, 255, 255));
        pInputs1.setLayout(new java.awt.GridLayout(3, 0, 0, 11));

        pEventPicker.setLayout(new javax.swing.BoxLayout(pEventPicker, javax.swing.BoxLayout.LINE_AXIS));

        cmbEvent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbEvent.setModel(eventModel);
        pEventPicker.add(cmbEvent);

        pInputs1.add(pEventPicker);

        jdcScheduleDate.setToolTipText("");
        jdcScheduleDate.setDate(new Date());
        jdcScheduleDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdcScheduleDate.setMinSelectableDate(new java.util.Date(-2208985112000L));
        pInputs1.add(jdcScheduleDate);

        jdcClosingDate.setToolTipText("");
        jdcClosingDate.setDate(new Date());
        jdcClosingDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jdcClosingDate.setMinSelectableDate(new java.util.Date(-2208985112000L));
        pInputs1.add(jdcClosingDate);

        javax.swing.GroupLayout pContent1Layout = new javax.swing.GroupLayout(pContent1);
        pContent1.setLayout(pContent1Layout);
        pContent1Layout.setHorizontalGroup(
            pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pLabels1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInputs1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pContent1Layout.setVerticalGroup(
            pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pEventDetailsLayout = new javax.swing.GroupLayout(pEventDetails);
        pEventDetails.setLayout(pEventDetailsLayout);
        pEventDetailsLayout.setHorizontalGroup(
            pEventDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pEventDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pEventDetailsLayout.createSequentialGroup()
                        .addComponent(pHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))))
        );
        pEventDetailsLayout.setVerticalGroup(
            pEventDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEventDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pConfirmArea.setBackground(new java.awt.Color(242, 242, 242));
        pConfirmArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pInputs.setBackground(new java.awt.Color(242, 242, 242));
        pInputs.setLayout(new java.awt.GridLayout(1, 1, 6, 4));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/tick.png"))); // NOI18N
        btnSave.setText("Create");
        btnSave.setIconTextGap(1);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pInputs.add(btnSave);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setIconTextGap(1);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pInputs.add(btnCancel);

        javax.swing.GroupLayout pConfirmAreaLayout = new javax.swing.GroupLayout(pConfirmArea);
        pConfirmArea.setLayout(pConfirmAreaLayout);
        pConfirmAreaLayout.setHorizontalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pConfirmAreaLayout.setVerticalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout pFormLayout = new javax.swing.GroupLayout(pForm);
        pForm.setLayout(pFormLayout);
        pFormLayout.setHorizontalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConfirmArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEventDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        pFormLayout.setVerticalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pEventDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pConfirmArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        addAdvert();
        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        isDisposing = true;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddAdvertisement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddAdvertisement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Event> cmbEvent;
    private com.toedter.calendar.JDateChooser jdcClosingDate;
    private com.toedter.calendar.JDateChooser jdcScheduleDate;
    private javax.swing.JLabel lbBookingDetails;
    private javax.swing.JLabel lbEvent;
    private javax.swing.JLabel lbUserEmail;
    private javax.swing.JLabel lbVenue;
    private javax.swing.JPanel pConfirmArea;
    private javax.swing.JPanel pContent1;
    private javax.swing.JPanel pEventDetails;
    private javax.swing.JPanel pEventPicker;
    private javax.swing.JPanel pForm;
    private javax.swing.JPanel pHeader1;
    private javax.swing.JPanel pInputs;
    private javax.swing.JPanel pInputs1;
    private javax.swing.JPanel pLabels1;
    // End of variables declaration//GEN-END:variables

}
