/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopappgui.Frames;

import adminDataModel.Address;
import adminDataModel.DataContainer;
import adminDataModel.Venue;
import java.awt.Color;
import validation.*;
import java.awt.Toolkit;
import validation.CustomValidator;

/**
 *
 * @author damdirtyape
 */
public class FormAddVenue extends javax.swing.JFrame {

    
    DataContainer admin = DataContainer.getInstance();

    public FormAddVenue() {
        initComponents();
        // Set custom visuals
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/addForm.png")));
        this.setLocationRelativeTo(null); // Centre window

        // <editor-fold defaultstate="collapsed" desc="Input Data Validation">      
        txtAddressLine1.setInputVerifier(new AlphaNumericalValidator(txtAddressLine1, 1, 35, false));
        txtAddressLine2.setInputVerifier(new AlphaNumericalValidator(txtAddressLine2, 0, 35, false));
        txtPostcode.setInputVerifier(new CustomValidator(txtPostcode, 6, 9, 
                "^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$", 
                true, "must be a postcode"));
        txtTownCity.setInputVerifier(new NameValidator(txtTownCity, 1, 35));
        // </editor-fold>
    }    

    private void createVenue() {
        Venue v = new Venue();
        Address a = new Address(txtAddressLine1.getText(), txtAddressLine2.getText(), txtTownCity.getText(), txtPostcode.getText());
        v.setAddress1(a);
        v.setDisabilityAccess('Y');
        v.setHasParking(ckbHasParking.isSelected() ? 'Y' : 'N');
        v.setTotalSeats((int) spnSeatCapacity.getValue());
        admin.addNewVenue(v);
    }

    private void validateForm() {
        Color isValidColor = new Color(224, 255, 224);
        Color isInvalidColor = new Color(255, 238, 238); 
        
        if (txtAddressLine1.getBackground().equals(isValidColor)
                && !txtAddressLine2.getBackground().equals(isInvalidColor)
                && txtPostcode.getBackground().equals(isValidColor)
                && txtTownCity.getBackground().equals(isValidColor)) {
                //createVenue();
                dispose();
        } else {
            txtAddressLine1.requestFocus();
            txtAddressLine2.requestFocus();
            txtPostcode.requestFocus();
            txtTownCity.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pForm = new javax.swing.JPanel();
        pVenueDetails = new javax.swing.JPanel();
        pHeader1 = new javax.swing.JPanel();
        lbCapacityDetails = new javax.swing.JLabel();
        pContent1 = new javax.swing.JPanel();
        pLabels1 = new javax.swing.JPanel();
        lbSeatCapacity = new javax.swing.JLabel();
        pInputs1 = new javax.swing.JPanel();
        spnSeatCapacity = new javax.swing.JSpinner();
        pLabels1a = new javax.swing.JPanel();
        lbHasParking = new javax.swing.JLabel();
        pInputs1a = new javax.swing.JPanel();
        ckbHasParking = new javax.swing.JCheckBox();
        pAddressDetails = new javax.swing.JPanel();
        pHeader3 = new javax.swing.JPanel();
        lbVenueDetails1 = new javax.swing.JLabel();
        pContent3 = new javax.swing.JPanel();
        pLabels3 = new javax.swing.JPanel();
        lbAddressLine1 = new javax.swing.JLabel();
        lbAddressLine2 = new javax.swing.JLabel();
        lbTownCity = new javax.swing.JLabel();
        lbPostcode = new javax.swing.JLabel();
        pInputs3 = new javax.swing.JPanel();
        txtAddressLine1 = new javax.swing.JTextField();
        txtAddressLine2 = new javax.swing.JTextField();
        txtTownCity = new javax.swing.JTextField();
        txtPostcode = new javax.swing.JFormattedTextField();
        pConfirmArea = new javax.swing.JPanel();
        pInputs = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Venue");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pForm.setBackground(new java.awt.Color(255, 255, 255));
        pForm.setForeground(new java.awt.Color(204, 204, 204));

        pVenueDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader1.setBackground(new java.awt.Color(255, 255, 255));

        lbCapacityDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbCapacityDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/venue.png"))); // NOI18N
        lbCapacityDetails.setText("Capacity Details");
        lbCapacityDetails.setToolTipText("");

        javax.swing.GroupLayout pHeader1Layout = new javax.swing.GroupLayout(pHeader1);
        pHeader1.setLayout(pHeader1Layout);
        pHeader1Layout.setHorizontalGroup(
            pHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCapacityDetails)
        );
        pHeader1Layout.setVerticalGroup(
            pHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCapacityDetails)
        );

        pContent1.setBackground(new java.awt.Color(255, 255, 255));
        pContent1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels1.setBackground(new java.awt.Color(255, 255, 255));
        pLabels1.setLayout(new java.awt.GridLayout(1, 1, 11, 11));

        lbSeatCapacity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSeatCapacity.setForeground(new java.awt.Color(42, 42, 42));
        lbSeatCapacity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSeatCapacity.setText("Seat Capacity*");
        lbSeatCapacity.setToolTipText("");
        pLabels1.add(lbSeatCapacity);

        pInputs1.setBackground(new java.awt.Color(255, 255, 255));
        pInputs1.setLayout(new java.awt.GridLayout(1, 0, 0, 11));

        spnSeatCapacity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnSeatCapacity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        pInputs1.add(spnSeatCapacity);

        pLabels1a.setBackground(new java.awt.Color(255, 255, 255));
        pLabels1a.setLayout(new java.awt.GridLayout(1, 1, 11, 11));

        lbHasParking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHasParking.setForeground(new java.awt.Color(42, 42, 42));
        lbHasParking.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbHasParking.setText("Has Parking");
        pLabels1a.add(lbHasParking);

        pInputs1a.setBackground(new java.awt.Color(255, 255, 255));
        pInputs1a.setLayout(new java.awt.GridLayout(1, 3, 5, 11));

        ckbHasParking.setBackground(new java.awt.Color(255, 255, 255));
        ckbHasParking.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbHasParking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));
        ckbHasParking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ckbHasParking.setIconTextGap(0);
        ckbHasParking.setMargin(new java.awt.Insets(2, 0, 2, 2));
        ckbHasParking.setName("Has Parking"); // NOI18N
        pInputs1a.add(ckbHasParking);

        javax.swing.GroupLayout pContent1Layout = new javax.swing.GroupLayout(pContent1);
        pContent1.setLayout(pContent1Layout);
        pContent1Layout.setHorizontalGroup(
            pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pContent1Layout.createSequentialGroup()
                        .addComponent(pLabels1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pInputs1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pContent1Layout.createSequentialGroup()
                        .addComponent(pLabels1a, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pInputs1a, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pContent1Layout.setVerticalGroup(
            pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels1a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pContent1Layout.createSequentialGroup()
                        .addComponent(pInputs1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pVenueDetailsLayout = new javax.swing.GroupLayout(pVenueDetails);
        pVenueDetails.setLayout(pVenueDetailsLayout);
        pVenueDetailsLayout.setHorizontalGroup(
            pVenueDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVenueDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pVenueDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pVenueDetailsLayout.setVerticalGroup(
            pVenueDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVenueDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pAddressDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader3.setBackground(new java.awt.Color(255, 255, 255));

        lbVenueDetails1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbVenueDetails1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/venue.png"))); // NOI18N
        lbVenueDetails1.setText("Venue Details");
        lbVenueDetails1.setToolTipText("");

        javax.swing.GroupLayout pHeader3Layout = new javax.swing.GroupLayout(pHeader3);
        pHeader3.setLayout(pHeader3Layout);
        pHeader3Layout.setHorizontalGroup(
            pHeader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeader3Layout.createSequentialGroup()
                .addComponent(lbVenueDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
        );
        pHeader3Layout.setVerticalGroup(
            pHeader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbVenueDetails1)
        );

        pContent3.setBackground(new java.awt.Color(255, 255, 255));
        pContent3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels3.setBackground(new java.awt.Color(255, 255, 255));
        pLabels3.setLayout(new java.awt.GridLayout(4, 1, 11, 11));

        lbAddressLine1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAddressLine1.setForeground(new java.awt.Color(42, 42, 42));
        lbAddressLine1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAddressLine1.setText("Address Line 1*");
        pLabels3.add(lbAddressLine1);

        lbAddressLine2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAddressLine2.setForeground(new java.awt.Color(42, 42, 42));
        lbAddressLine2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAddressLine2.setText("Address Line 2");
        lbAddressLine2.setToolTipText("");
        pLabels3.add(lbAddressLine2);

        lbTownCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTownCity.setForeground(new java.awt.Color(42, 42, 42));
        lbTownCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTownCity.setText("Town/City*");
        lbTownCity.setToolTipText("");
        pLabels3.add(lbTownCity);

        lbPostcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPostcode.setForeground(new java.awt.Color(42, 42, 42));
        lbPostcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPostcode.setText("Postcode*");
        pLabels3.add(lbPostcode);

        pInputs3.setBackground(new java.awt.Color(255, 255, 255));
        pInputs3.setLayout(new java.awt.GridLayout(4, 0, 0, 11));

        txtAddressLine1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddressLine1.setName("Address Line 1"); // NOI18N
        pInputs3.add(txtAddressLine1);

        txtAddressLine2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddressLine2.setName("Address Line 2"); // NOI18N
        pInputs3.add(txtAddressLine2);

        txtTownCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTownCity.setName("Town/City"); // NOI18N
        pInputs3.add(txtTownCity);

        txtPostcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPostcode.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        txtPostcode.setName("Postcode"); // NOI18N
        pInputs3.add(txtPostcode);

        javax.swing.GroupLayout pContent3Layout = new javax.swing.GroupLayout(pContent3);
        pContent3.setLayout(pContent3Layout);
        pContent3Layout.setHorizontalGroup(
            pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContent3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pLabels3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInputs3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pContent3Layout.setVerticalGroup(
            pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pAddressDetailsLayout = new javax.swing.GroupLayout(pAddressDetails);
        pAddressDetails.setLayout(pAddressDetailsLayout);
        pAddressDetailsLayout.setHorizontalGroup(
            pAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddressDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pAddressDetailsLayout.setVerticalGroup(
            pAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddressDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pConfirmArea.setBackground(new java.awt.Color(242, 242, 242));
        pConfirmArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pInputs.setBackground(new java.awt.Color(242, 242, 242));
        pInputs.setLayout(new java.awt.GridLayout(1, 1, 6, 4));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/tick.png"))); // NOI18N
        btnSave.setText("Create");
        btnSave.setIconTextGap(1);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pInputs.add(btnSave);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setIconTextGap(1);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pInputs.add(btnCancel);

        javax.swing.GroupLayout pConfirmAreaLayout = new javax.swing.GroupLayout(pConfirmArea);
        pConfirmArea.setLayout(pConfirmAreaLayout);
        pConfirmAreaLayout.setHorizontalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pConfirmAreaLayout.setVerticalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout pFormLayout = new javax.swing.GroupLayout(pForm);
        pForm.setLayout(pFormLayout);
        pFormLayout.setHorizontalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConfirmArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pVenueDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pAddressDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pFormLayout.setVerticalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAddressDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pVenueDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pConfirmArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        validateForm();
        createVenue();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddVenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddVenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox ckbHasParking;
    private javax.swing.JLabel lbAddressLine1;
    private javax.swing.JLabel lbAddressLine2;
    private javax.swing.JLabel lbCapacityDetails;
    private javax.swing.JLabel lbHasParking;
    private javax.swing.JLabel lbPostcode;
    private javax.swing.JLabel lbSeatCapacity;
    private javax.swing.JLabel lbTownCity;
    private javax.swing.JLabel lbVenueDetails1;
    private javax.swing.JPanel pAddressDetails;
    private javax.swing.JPanel pConfirmArea;
    private javax.swing.JPanel pContent1;
    private javax.swing.JPanel pContent3;
    private javax.swing.JPanel pForm;
    private javax.swing.JPanel pHeader1;
    private javax.swing.JPanel pHeader3;
    private javax.swing.JPanel pInputs;
    private javax.swing.JPanel pInputs1;
    private javax.swing.JPanel pInputs1a;
    private javax.swing.JPanel pInputs3;
    private javax.swing.JPanel pLabels1;
    private javax.swing.JPanel pLabels1a;
    private javax.swing.JPanel pLabels3;
    private javax.swing.JPanel pVenueDetails;
    private javax.swing.JSpinner spnSeatCapacity;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JFormattedTextField txtPostcode;
    private javax.swing.JTextField txtTownCity;
    // End of variables declaration//GEN-END:variables

}
