/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopappgui.Frames;

import adminDataModel.DataContainer;
import adminDataModel.Address;
import adminDataModel.Customer;
import java.awt.Color;
import validation.*;
import java.awt.Toolkit;
import java.time.ZoneId;
import java.util.Date;
import validation.CustomValidator;

/**
 *
 * @author damdirtyape
 */
public class FormAddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddUserFramea
     */
    
    private DataContainer peopleList;        
    public FormAddCustomer() {
        
        peopleList = DataContainer.getInstance();
        initComponents();
        
        // Set custom visuals
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/addForm.png")));
        this.setLocationRelativeTo(null); // Centre window
        
        // <editor-fold defaultstate="collapsed" desc="Input Data Validation">
        txtForename.setInputVerifier(new NameValidator(txtForename, 1, 35));        
        txtSurname.setInputVerifier(new NameValidator(txtSurname, 1, 35));             
        txtEmailAddress.setInputVerifier(new EmailValidator(txtEmailAddress));
        txtMobileNo.setInputVerifier(new MobileNumberValidator(txtMobileNo));
        txtAddressLine1.setInputVerifier(new AlphaNumericalValidator(txtAddressLine1, 1, 35, false));
        txtAddressLine2.setInputVerifier(new AlphaNumericalValidator(txtAddressLine2, 0, 35, false));   
        txtTownCity.setInputVerifier(new NameValidator(txtTownCity, 1, 35));
        txtPostcode.setInputVerifier(new CustomValidator(txtPostcode, 6, 8, 
                "^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$", 
                true, "must be a postcode"));
        txtPassword.setInputVerifier(new CustomValidator(txtPassword, 7, 35, 
                "^$", false, 
                "should be secure and therefore"));
       // </editor-fold>
    }
    
    private void addUser() {
        Customer p = new Customer();
        Address a;
        p.setGivenName(txtForename.getText());
        p.setFamilyName(txtSurname.getText());
        p.setEmail(txtEmailAddress.getText());
        p.setMobileNumber(txtMobileNo.getText());
        p.setDateOfBirth(jdcDOB.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        a = new Address(txtAddressLine1.getText(), txtAddressLine2.getText(), txtTownCity.getText(), txtPostcode.getText());
        p.setAddress(a);
        p.setPassword(new String(txtPassword.getPassword()));
        peopleList.addNewCustomer(p);
    }      
    
    public void setEmail(String email) {
        txtEmailAddress.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pForm = new javax.swing.JPanel();
        pIdentificationDetails = new javax.swing.JPanel();
        pHeader1 = new javax.swing.JPanel();
        lbIdentificationDetails = new javax.swing.JLabel();
        pContent1 = new javax.swing.JPanel();
        pLabels1 = new javax.swing.JPanel();
        lbForename = new javax.swing.JLabel();
        lbSurname = new javax.swing.JLabel();
        pInputs1 = new javax.swing.JPanel();
        txtForename = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        pLabels1a = new javax.swing.JPanel();
        lbDOB = new javax.swing.JLabel();
        pInputs1a = new javax.swing.JPanel();
        jdcDOB = new com.toedter.calendar.JDateChooser();
        pContactDetails = new javax.swing.JPanel();
        pHeader2 = new javax.swing.JPanel();
        lbContactDetails = new javax.swing.JLabel();
        pContent2 = new javax.swing.JPanel();
        pLabels2 = new javax.swing.JPanel();
        lbEmailAddress = new javax.swing.JLabel();
        lbMobileNo = new javax.swing.JLabel();
        pInputs2 = new javax.swing.JPanel();
        txtEmailAddress = new javax.swing.JFormattedTextField();
        txtMobileNo = new javax.swing.JFormattedTextField();
        pAddressDetails = new javax.swing.JPanel();
        pHeader3 = new javax.swing.JPanel();
        lbAddressDetails = new javax.swing.JLabel();
        pContent3 = new javax.swing.JPanel();
        pLabels3 = new javax.swing.JPanel();
        lbAddressLine1 = new javax.swing.JLabel();
        lbAddressLine2 = new javax.swing.JLabel();
        lbTownCity = new javax.swing.JLabel();
        lbPostcode = new javax.swing.JLabel();
        pInputs3 = new javax.swing.JPanel();
        txtAddressLine1 = new javax.swing.JTextField();
        txtAddressLine2 = new javax.swing.JTextField();
        txtTownCity = new javax.swing.JTextField();
        txtPostcode = new javax.swing.JFormattedTextField();
        pSecurityDetails = new javax.swing.JPanel();
        pHeader4 = new javax.swing.JPanel();
        lbSecurityDetails = new javax.swing.JLabel();
        pContent4 = new javax.swing.JPanel();
        pLabels4 = new javax.swing.JPanel();
        lbPassword = new javax.swing.JLabel();
        lbPasswordAgain = new javax.swing.JLabel();
        pInputs4 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordAgain = new javax.swing.JPasswordField();
        pConfirmArea = new javax.swing.JPanel();
        pInputs = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Customer");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pForm.setBackground(new java.awt.Color(255, 255, 255));
        pForm.setForeground(new java.awt.Color(204, 204, 204));

        pIdentificationDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader1.setBackground(new java.awt.Color(255, 255, 255));

        lbIdentificationDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbIdentificationDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/personalInfo.png"))); // NOI18N
        lbIdentificationDetails.setText("Identification Details");
        lbIdentificationDetails.setToolTipText("");

        javax.swing.GroupLayout pHeader1Layout = new javax.swing.GroupLayout(pHeader1);
        pHeader1.setLayout(pHeader1Layout);
        pHeader1Layout.setHorizontalGroup(
            pHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIdentificationDetails)
        );
        pHeader1Layout.setVerticalGroup(
            pHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIdentificationDetails)
        );

        pContent1.setBackground(new java.awt.Color(255, 255, 255));
        pContent1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels1.setBackground(new java.awt.Color(255, 255, 255));
        pLabels1.setLayout(new java.awt.GridLayout(2, 1, 11, 11));

        lbForename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbForename.setForeground(new java.awt.Color(42, 42, 42));
        lbForename.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbForename.setText("Forename*");
        pLabels1.add(lbForename);

        lbSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSurname.setForeground(new java.awt.Color(42, 42, 42));
        lbSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSurname.setText("Surname*");
        pLabels1.add(lbSurname);

        pInputs1.setBackground(new java.awt.Color(255, 255, 255));
        pInputs1.setLayout(new java.awt.GridLayout(2, 0, 0, 11));

        txtForename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtForename.setName("Forename"); // NOI18N
        pInputs1.add(txtForename);

        txtSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSurname.setName("Surname"); // NOI18N
        pInputs1.add(txtSurname);

        pLabels1a.setBackground(new java.awt.Color(255, 255, 255));
        pLabels1a.setLayout(new java.awt.GridLayout(1, 1, 11, 11));

        lbDOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDOB.setForeground(new java.awt.Color(42, 42, 42));
        lbDOB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDOB.setText("DOB*");
        pLabels1a.add(lbDOB);

        pInputs1a.setBackground(new java.awt.Color(255, 255, 255));
        pInputs1a.setLayout(new java.awt.GridLayout(1, 1, 5, 11));

        jdcDOB.setToolTipText("");
        jdcDOB.setDate(new Date());
        jdcDOB.setMaxSelectableDate(new Date());
        jdcDOB.setMinSelectableDate(new java.util.Date(-2208985112000L));
        pInputs1a.add(jdcDOB);

        javax.swing.GroupLayout pContent1Layout = new javax.swing.GroupLayout(pContent1);
        pContent1.setLayout(pContent1Layout);
        pContent1Layout.setHorizontalGroup(
            pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pContent1Layout.createSequentialGroup()
                        .addComponent(pLabels1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pInputs1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pContent1Layout.createSequentialGroup()
                        .addComponent(pLabels1a, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pInputs1a, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pContent1Layout.setVerticalGroup(
            pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels1a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pContent1Layout.createSequentialGroup()
                        .addComponent(pInputs1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pIdentificationDetailsLayout = new javax.swing.GroupLayout(pIdentificationDetails);
        pIdentificationDetails.setLayout(pIdentificationDetailsLayout);
        pIdentificationDetailsLayout.setHorizontalGroup(
            pIdentificationDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificationDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pIdentificationDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pIdentificationDetailsLayout.setVerticalGroup(
            pIdentificationDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificationDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pContactDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader2.setBackground(new java.awt.Color(255, 255, 255));

        lbContactDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbContactDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/contact.png"))); // NOI18N
        lbContactDetails.setText("Contact Details");
        lbContactDetails.setToolTipText("");

        javax.swing.GroupLayout pHeader2Layout = new javax.swing.GroupLayout(pHeader2);
        pHeader2.setLayout(pHeader2Layout);
        pHeader2Layout.setHorizontalGroup(
            pHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pHeader2Layout.setVerticalGroup(
            pHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbContactDetails)
        );

        pContent2.setBackground(new java.awt.Color(255, 255, 255));
        pContent2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels2.setBackground(new java.awt.Color(255, 255, 255));
        pLabels2.setLayout(new java.awt.GridLayout(2, 1, 11, 11));

        lbEmailAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEmailAddress.setForeground(new java.awt.Color(42, 42, 42));
        lbEmailAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmailAddress.setText("Email Address*");
        lbEmailAddress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pLabels2.add(lbEmailAddress);

        lbMobileNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMobileNo.setForeground(new java.awt.Color(42, 42, 42));
        lbMobileNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMobileNo.setText("Mobile No");
        lbMobileNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pLabels2.add(lbMobileNo);

        pInputs2.setBackground(new java.awt.Color(255, 255, 255));
        pInputs2.setLayout(new java.awt.GridLayout(2, 0, 0, 11));

        txtEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmailAddress.setName("Email Address"); // NOI18N
        pInputs2.add(txtEmailAddress);

        txtMobileNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMobileNo.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        txtMobileNo.setName("Mobile No"); // NOI18N
        pInputs2.add(txtMobileNo);

        javax.swing.GroupLayout pContent2Layout = new javax.swing.GroupLayout(pContent2);
        pContent2.setLayout(pContent2Layout);
        pContent2Layout.setHorizontalGroup(
            pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContent2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pLabels2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInputs2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pContent2Layout.setVerticalGroup(
            pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pContactDetailsLayout = new javax.swing.GroupLayout(pContactDetails);
        pContactDetails.setLayout(pContactDetailsLayout);
        pContactDetailsLayout.setHorizontalGroup(
            pContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContactDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pContactDetailsLayout.setVerticalGroup(
            pContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContactDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pAddressDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader3.setBackground(new java.awt.Color(255, 255, 255));

        lbAddressDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbAddressDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/address.png"))); // NOI18N
        lbAddressDetails.setText("Address Details");
        lbAddressDetails.setToolTipText("");

        javax.swing.GroupLayout pHeader3Layout = new javax.swing.GroupLayout(pHeader3);
        pHeader3.setLayout(pHeader3Layout);
        pHeader3Layout.setHorizontalGroup(
            pHeader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeader3Layout.createSequentialGroup()
                .addComponent(lbAddressDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
        );
        pHeader3Layout.setVerticalGroup(
            pHeader3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAddressDetails)
        );

        pContent3.setBackground(new java.awt.Color(255, 255, 255));
        pContent3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels3.setBackground(new java.awt.Color(255, 255, 255));
        pLabels3.setLayout(new java.awt.GridLayout(4, 1, 11, 11));

        lbAddressLine1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAddressLine1.setForeground(new java.awt.Color(42, 42, 42));
        lbAddressLine1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAddressLine1.setText("Address Line 1*");
        pLabels3.add(lbAddressLine1);

        lbAddressLine2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAddressLine2.setForeground(new java.awt.Color(51, 51, 51));
        lbAddressLine2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAddressLine2.setText("Address Line 2  ");
        pLabels3.add(lbAddressLine2);

        lbTownCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTownCity.setForeground(new java.awt.Color(42, 42, 42));
        lbTownCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTownCity.setText("Town/City*");
        pLabels3.add(lbTownCity);

        lbPostcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPostcode.setForeground(new java.awt.Color(42, 42, 42));
        lbPostcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPostcode.setText("Postcode*");
        pLabels3.add(lbPostcode);

        pInputs3.setBackground(new java.awt.Color(255, 255, 255));
        pInputs3.setLayout(new java.awt.GridLayout(4, 0, 0, 11));

        txtAddressLine1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddressLine1.setName("Address Line 1"); // NOI18N
        pInputs3.add(txtAddressLine1);

        txtAddressLine2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddressLine2.setName("Address Line 2"); // NOI18N
        pInputs3.add(txtAddressLine2);

        txtTownCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTownCity.setName("Town/City"); // NOI18N
        pInputs3.add(txtTownCity);

        txtPostcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPostcode.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        txtPostcode.setName("Postcode"); // NOI18N
        pInputs3.add(txtPostcode);

        javax.swing.GroupLayout pContent3Layout = new javax.swing.GroupLayout(pContent3);
        pContent3.setLayout(pContent3Layout);
        pContent3Layout.setHorizontalGroup(
            pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContent3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pLabels3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInputs3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pContent3Layout.setVerticalGroup(
            pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pAddressDetailsLayout = new javax.swing.GroupLayout(pAddressDetails);
        pAddressDetails.setLayout(pAddressDetailsLayout);
        pAddressDetailsLayout.setHorizontalGroup(
            pAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddressDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pAddressDetailsLayout.setVerticalGroup(
            pAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddressDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pSecurityDetails.setBackground(new java.awt.Color(255, 255, 255));

        pHeader4.setBackground(new java.awt.Color(255, 255, 255));

        lbSecurityDetails.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbSecurityDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/security.png"))); // NOI18N
        lbSecurityDetails.setText("Security Details");
        lbSecurityDetails.setToolTipText("");

        javax.swing.GroupLayout pHeader4Layout = new javax.swing.GroupLayout(pHeader4);
        pHeader4.setLayout(pHeader4Layout);
        pHeader4Layout.setHorizontalGroup(
            pHeader4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSecurityDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pHeader4Layout.setVerticalGroup(
            pHeader4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSecurityDetails)
        );

        pContent4.setBackground(new java.awt.Color(255, 255, 255));
        pContent4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pLabels4.setBackground(new java.awt.Color(255, 255, 255));
        pLabels4.setLayout(new java.awt.GridLayout(2, 1, 11, 11));

        lbPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(51, 51, 51));
        lbPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPassword.setText("Password*");
        pLabels4.add(lbPassword);

        lbPasswordAgain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPasswordAgain.setForeground(new java.awt.Color(42, 42, 42));
        lbPasswordAgain.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPasswordAgain.setText("Re-Entry*");
        pLabels4.add(lbPasswordAgain);

        pInputs4.setBackground(new java.awt.Color(255, 255, 255));
        pInputs4.setLayout(new java.awt.GridLayout(2, 0, 0, 11));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassword.setName("Password"); // NOI18N
        pInputs4.add(txtPassword);

        txtPasswordAgain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPasswordAgain.setName("Password Re-Entry"); // NOI18N
        txtPasswordAgain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordAgainFocusLost(evt);
            }
        });
        pInputs4.add(txtPasswordAgain);

        javax.swing.GroupLayout pContent4Layout = new javax.swing.GroupLayout(pContent4);
        pContent4.setLayout(pContent4Layout);
        pContent4Layout.setHorizontalGroup(
            pContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContent4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pLabels4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInputs4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pContent4Layout.setVerticalGroup(
            pContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContent4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLabels4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pInputs4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pSecurityDetailsLayout = new javax.swing.GroupLayout(pSecurityDetails);
        pSecurityDetails.setLayout(pSecurityDetailsLayout);
        pSecurityDetailsLayout.setHorizontalGroup(
            pSecurityDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSecurityDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pSecurityDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pContent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        pSecurityDetailsLayout.setVerticalGroup(
            pSecurityDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSecurityDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pContent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pConfirmArea.setBackground(new java.awt.Color(242, 242, 242));
        pConfirmArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pInputs.setBackground(new java.awt.Color(242, 242, 242));
        pInputs.setLayout(new java.awt.GridLayout(1, 1, 6, 4));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/tick.png"))); // NOI18N
        btnSave.setText("Create");
        btnSave.setIconTextGap(1);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pInputs.add(btnSave);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setIconTextGap(1);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pInputs.add(btnCancel);

        javax.swing.GroupLayout pConfirmAreaLayout = new javax.swing.GroupLayout(pConfirmArea);
        pConfirmArea.setLayout(pConfirmAreaLayout);
        pConfirmAreaLayout.setHorizontalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pConfirmAreaLayout.setVerticalGroup(
            pConfirmAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfirmAreaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout pFormLayout = new javax.swing.GroupLayout(pForm);
        pForm.setLayout(pFormLayout);
        pFormLayout.setHorizontalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pSecurityDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pIdentificationDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pContactDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAddressDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(pConfirmArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pFormLayout.setVerticalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pIdentificationDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pAddressDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pSecurityDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pConfirmArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void validateForm() {
        Color isValidColor = new Color(224, 255, 224);
        Color isInvalidColor = new Color(255, 238, 238);
        
        if (txtForename.getBackground().equals(isValidColor)
                && txtSurname.getBackground().equals(isValidColor)
                && txtEmailAddress.getBackground().equals(isValidColor)
                && (txtMobileNo.getBackground().equals(isValidColor)
                || !txtMobileNo.getBackground().equals(isInvalidColor))
                && txtAddressLine1.getBackground().equals(isValidColor)
                && !txtAddressLine2.getBackground().equals(isInvalidColor)
                && txtPostcode.getBackground().equals(isValidColor)
                && txtPassword.getBackground().equals(isValidColor)
                && txtPasswordAgain.getBackground().equals(isValidColor)
                ) {
            addUser();
            dispose();
        } else {
            txtForename.requestFocus();
            txtSurname.requestFocus();
            txtEmailAddress.requestFocus();
            txtMobileNo.requestFocus();
            txtAddressLine1.requestFocus();
            txtAddressLine2.requestFocus();
            txtPostcode.requestFocus();
            txtPassword.requestFocus();
            txtPasswordAgain.requestFocus();
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        validateForm();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPasswordAgainFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordAgainFocusLost
        new ReEntryValidator(txtPasswordAgain, 0, 0, txtPassword, "must be same as password").shouldYieldFocus(txtPasswordAgain);
    }//GEN-LAST:event_txtPasswordAgainFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jdcDOB;
    private javax.swing.JLabel lbAddressDetails;
    private javax.swing.JLabel lbAddressLine1;
    private javax.swing.JLabel lbAddressLine2;
    private javax.swing.JLabel lbContactDetails;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbEmailAddress;
    private javax.swing.JLabel lbForename;
    private javax.swing.JLabel lbIdentificationDetails;
    private javax.swing.JLabel lbMobileNo;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPasswordAgain;
    private javax.swing.JLabel lbPostcode;
    private javax.swing.JLabel lbSecurityDetails;
    private javax.swing.JLabel lbSurname;
    private javax.swing.JLabel lbTownCity;
    private javax.swing.JPanel pAddressDetails;
    private javax.swing.JPanel pConfirmArea;
    private javax.swing.JPanel pContactDetails;
    private javax.swing.JPanel pContent1;
    private javax.swing.JPanel pContent2;
    private javax.swing.JPanel pContent3;
    private javax.swing.JPanel pContent4;
    private javax.swing.JPanel pForm;
    private javax.swing.JPanel pHeader1;
    private javax.swing.JPanel pHeader2;
    private javax.swing.JPanel pHeader3;
    private javax.swing.JPanel pHeader4;
    private javax.swing.JPanel pIdentificationDetails;
    private javax.swing.JPanel pInputs;
    private javax.swing.JPanel pInputs1;
    private javax.swing.JPanel pInputs1a;
    private javax.swing.JPanel pInputs2;
    private javax.swing.JPanel pInputs3;
    private javax.swing.JPanel pInputs4;
    private javax.swing.JPanel pLabels1;
    private javax.swing.JPanel pLabels1a;
    private javax.swing.JPanel pLabels2;
    private javax.swing.JPanel pLabels3;
    private javax.swing.JPanel pLabels4;
    private javax.swing.JPanel pSecurityDetails;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JFormattedTextField txtEmailAddress;
    private javax.swing.JTextField txtForename;
    private javax.swing.JFormattedTextField txtMobileNo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordAgain;
    private javax.swing.JFormattedTextField txtPostcode;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTownCity;
    // End of variables declaration//GEN-END:variables
}
